### ISSUE TITLE
这代码排序有问题，不能循环所有会议列表的。

### ISSUE THREAD

**Issue by Michael1021** [xcbeyond/ConferenceTrackManagement#2]
1. 按照会议时间长度排序，如果剩余的会议时间长度30分钟，而刚好循环的下个会议是大于30分钟的，代码就直接break了，那就有会议没安排上。

**Comment by xcbeyond** [comment]
排序本身是没有问题的

**Comment by xcbeyond** [comment]
排序本身是没有问题的 @Michael1021

**Comment by Michael1021** [comment]
你程序跑一下就知道了，你代码运行出来少两个会议。跟踪了一下，你是按照会议长度大小排序，如果第一个Track 的 下午240分钟没有安排满，当剩余时间为30分钟时，下一场会议的时间是45分钟，直接就break了。

**Comment by xcbeyond** [comment]
> 下午240分钟没有安排满，当剩余时间为30分钟时，下一场会议的时间是45分钟，直接就break了
这逻辑没问题呀，题目要求就是这样的。
不知道 你有没有看这个题目的要求？还是说 你的题目和我这题目的要求是存在细微差异的
你现在看见的程序，是通过Pair Program 环节考验的，基本功能要求还是OK的

**Comment by Michael1021** [comment]
![image](https://user-images.githubusercontent.com/30429589/100544429-7d12de00-3290-11eb-800b-0de4e4bf1a21.png)
你看，这是你代码跑出来的会议，按照题目 ，那个5分钟的闪电会议和一个30分钟的会议都没安排进去。【题目都是一样的】，

就算下午的会议是45分钟，break ，也应该是在第二个track显示会议啊。可是第二个track也没显示会议。

**Comment by xcbeyond** [comment]
@Michael1021 
> 你看，这是你代码跑出来的会议，按照题目 ，那个5分钟的闪电会议和一个30分钟的会议都没安排进去。【题目都是一样的】，
> 就算下午的会议是45分钟，break ，也应该是在第二个track显示会议啊。可是第二个track也没显示会议。

你说的是把具体哪个 没有安排进去，具体标注下、说明下。 从你运行的结果来看，没看出有啥问题呀

**Comment by Michael1021** [comment]
题目 有19个会议列表，代码运行出来的只有18个。Rails for Python Developers lightning，这个会议没有列出来。

**Comment by xcbeyond** [comment]
@Michael1021 从你运行的结果来看 的确是不对的。刚一直是用的我本地仓库的代码，运行发现也没有任何问题，对比才发现原来是本地代码commit了，当时忘记push啦，刚push上去了，你更新一下代码 就OK啦

**Comment by Michael1021** [comment]
赞赞赞

**Comment by xcbeyond** [comment]
@Michael1021 从你运行的结果来看 的确是不对的。刚一直是用的我本地仓库的代码，运行发现也没有任何问题，对比才发现原来是本地代码commit了，当时忘记push啦，刚push上去了，你更新一下代码 就OK啦
